version: "3.9"

networks:
  clipai_net:
    external: true
    name: clipai_net

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    image: gig-ai-admin:prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      clipai_net:
        aliases:
          - app
